article/urls.py
from django.contrib import admin
from django.urls import path
from . import views
from django.conf.urls.static import static
from django.conf import settings
app_name = "article"
urlpatterns = [
    path('dashboard/',views.dashboard,name = "dashboard"),
    path('premium/',views.premium,name = "premium"),
    path('checkout/',views.checkout,name = "checkout"),
    path('addarticle/',views.addarticle,name = "addarticle"),
    path('article/<int:id>',views.detail,name = "detail"),
    path('update/<int:id>',views.updateArticle,name = "update"),
    path('delete/<int:id>',views.deleteArticle,name = "delete"),
    path('',views.articles,name = "articles"),
    path('comment/<int:id>',views.addComment,name = "comment"),




]
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

blog/urls.py
from django.contrib import admin
from django.urls import path,include
from article import views
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.index,name = "index"),
    path('articles/',include("article.urls")),
    path('user/',include("user.urls")),
    


]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

user/urls.py
from django.contrib import admin
from django.urls import path
from . import views

app_name = "user"
urlpatterns = [
    path('register/',views.register,name = "register"),
    path('login/',views.loginUser,name = "login"),
    path('logout/',views.logoutUser,name = "logout"),
    
    
    
    
]

article/models.py
from django.db import models
from ckeditor.fields import RichTextField
# Create your models here.

class Article(models.Model):
    author = models.ForeignKey("auth.User",on_delete = models.CASCADE ) #verbose_name = "" yazıp içine girdiğimiz değeri isim olarak yazdırabiliriz.
    title = models.CharField(max_length=50)
    content = RichTextField()
    created_date = models.DateTimeField(auto_now_add=True)
    article_image = models.FileField(blank= True,null = True,verbose_name="Makaleye Fotoğraf Ekleyin")
    def __str__(self):
        return self.title

    class Meta:
        ordering = ['-created_date']
class Comment(models.Model):
    article = models.ForeignKey(Article,on_delete=models.CASCADE,verbose_name="Makale",related_name="comments")
    comment_author = models.CharField(max_length=50, verbose_name="İsim")
    comment_content = models.CharField(max_length=200 , verbose_name="Yorum")
    comment_date= models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.comment_content
    class Meta:
        ordering = ['-comment_date']

    

article/forms.py
from django import forms
from .models import Article
class ArticleForm(forms.ModelForm):
    class Meta:
        model = Article
        fields = ["title","content","article_image"]

article/views.py
from django.shortcuts import render,HttpResponse,redirect,get_object_or_404,reverse
from .forms import ArticleForm
from .models import Article,Comment
from django.contrib import messages
from django.contrib.auth.decorators import login_required
# Create your views here.

def articles(request):
    keyword = request.GET.get("keyword")

    if keyword:
        articles = Article.objects.filter(title__contains = keyword)
        return render(request,"articles.html",{"articles":articles})
    articles = Article.objects.all()

    return render(request,"articles.html", {"articles" : articles})

def index(request):
    return render(request,"index.html")
def premium(request):
    return render(request,"premium.html")
def checkout(request):
    return render(request,"checkout.html")
def about(request):
    return render(request,"about.html")
@login_required(login_url = "user:login") # Login required fonksiyonu giriş yapmadığımız zamanlarda dashboard, addarticle gibi sayfalara girmeyi engelleyip ekranı login ekranına yönlendirir.
def dashboard(request):
    articles = Article.objects.filter(author = request.user)

    context = {
        "articles" : articles
    }

    return render(request,"dashboard.html",context)


@login_required(login_url = "user:login")
def addarticle(request):
    form = ArticleForm(request.POST or None,request.FILES or None)

    if form.is_valid():
        article = form.save(commit = False)
        article.author = request.user
        article.save()
        messages.success(request,"Makale başarıyla oluşturuldu.")
        return redirect("index")
    return render(request,"addarticle.html",{"form": form})

def detail(request,id):
    #article = Article.objects.filter(id = id).first()
    article = get_object_or_404(Article,id = id)
    comments=article.comments.all()
    return render(request,"detail.html",{"article":article,"comments":comments})


@login_required(login_url = "user:login")
def updateArticle(request,id):
    article = get_object_or_404(Article,id=id)
    form = ArticleForm(request.POST or None,request.FILES or None,instance=article)
    if form.is_valid():
        article = form.save(commit = False)
        article.author = request.user
        article.save()
        messages.success(request,"Makale başarıyla güncellendi.")
        return redirect("index")
    

    return render(request,"update.html",{"form":form})

@login_required(login_url = "user:login")
def deleteArticle(request,id):
    article = get_object_or_404(Article,id = id)
    article.delete()
    messages.success(request,"Makale Başarıyla silindi..")

    return redirect("article:dashboard")

def addComment(request,id):
    article = get_object_or_404(Article,id = id)
    if request.method == "POST":
        comment_author = request.POST.get("comment_author")
        comment_content= request.POST.get("comment_content")
        newComment = Comment(comment_author = comment_author,comment_content = comment_content)
        newComment.article = article

        newComment.save()

    return redirect(reverse("article:detail",kwargs={"id":id})) #articles/detail/15 

templates/addarticle.html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <link rel="stylesheet" href="https://www.w3schools.com/w3css/4/w3.css">
  <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Lato">
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
  <title>Document</title>
  <div class="w3-bar" id="myNavbar">
    <a class="w3-bar-item w3-button w3-hover-black w3-hide-medium w3-hide-large w3-right" href="javascript:void(0);" onclick="toggleFunction()" title="Toggle Navigation Menu">
        <i class="fa fa-bars"></i>
      </a>
      <a href="{% url 'index' %}" class="w3-bar-item w3-button" style = "font-size:20px">PysonBlog ✓</a>
      <a  href="{% url 'article:articles' %}" class="w3-bar-item w3-button w3-hide-small" style = "font-size:20px"><i class="fa fa-clipboard" aria-hidden="true"></i>Articles</a>
      {% if request.user.is_authenticated %}
      <a  href="{% url 'article:dashboard' %}" class="w3-bar-item w3-button w3-hide-small"style = "font-size:20px"><i class="fa fa-wrench" aria-hidden="true"></i>Control Panel</a>
      <a  href="{% url 'user:logout' %}" class="w3-bar-item w3-button w3-hide-small"style = "font-size:20px"><i class="fa fa-power-off" aria-hidden="true"></i> Logout</a>
  
      {% else %}
      <a href="{% url 'user:login' %}" class="w3-bar-item w3-button w3-hide-small"style = "font-size:20px"><i class="fa fa-sign-in" aria-hidden="true"></i>Login</a>
      {% endif %}
        <a href="{% url 'user:register' %} " class="w3-bar-item w3-button w3-hide-small"style = "font-size:20px"><i class="fa fa-sign-out" aria-hidden="true"></i>Register </a>
        
  
     
</div>
  {% if messages %}

            {% for message in messages %}
            {% if message.tags == "info"%}
            <div class="alert alert-danger">{{ message }}</div>
            {% else %}
            <div class="alert alert-{{ message.tags }}">{{ message }}</div>
            
            {% endif %}
           
            {% endfor %}
            
        
        {% endif %}
        <div style = "margin-top : 100px; margin-bottom:100px"  class = "container">
       

{% block body %}
{%load crispy_forms_tags%}
<div class="row">
    <div class="col-md-6 offset-md-3">
        <h3>Makale Oluştur</h3>
        <hr>
        {% load crispy_forms_tags %}

        <form method="POST" enctype="multipart/form-data">


            {% csrf_token %}
            {{form.media}}
            
            {{form|crispy}}
            <br>
            <button type = "submit1" class = "btn btn-danger">Oluştur</button>
        
        </form>

    </div>
  </div>


{% endblock body %}

templates/articles.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="https://www.w3schools.com/w3css/4/w3.css">
    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Lato">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">

<style>

    .card {
        box-shadow: 0 4px 8px 0 rgba(0, 0, 0, 0.2);
        max-width: 300px;
        margin: auto;
        text-align: center;
        background-color: white;
      }
      
      .title {
        color: black;
        font-size: 18px;
      }
      
      button {
        border: none;
        outline: 0;
        display: inline-block;
        padding: 8px;
        color: white;
        background-color: #000;
        text-align: center;
        cursor: pointer;
        width: 100%;
        font-size: 18px;
      }
      
      a {
        text-decoration: none;
        font-size: 22px;
        color: black;
      }
      
      button:hover, a:hover {
        opacity: 0.7;
      }
     

</style>


{% block body %}

<div class="w3-bar" id="myNavbar">
    <a class="w3-bar-item w3-button w3-hover-black w3-hide-medium w3-hide-large w3-right" href="javascript:void(0);" onclick="toggleFunction()" title="Toggle Navigation Menu">
        <i class="fa fa-bars"></i>
      </a>
      <a href="{% url 'index' %}" class="w3-bar-item w3-button" style = "font-size:20px">PysonBlog ✓</a>
      <a  href="{% url 'article:articles' %}" class="w3-bar-item w3-button w3-hide-small" style = "font-size:20px"><i class="fa fa-clipboard" aria-hidden="true"></i>Articles</a>
      {% if request.user.is_authenticated %}
      <a  href="{% url 'article:dashboard' %}" class="w3-bar-item w3-button w3-hide-small"style = "font-size:20px"><i class="fa fa-wrench" aria-hidden="true"></i>Control Panel</a>
      <a  href="{% url 'user:logout' %}" class="w3-bar-item w3-button w3-hide-small"style = "font-size:20px"><i class="fa fa-power-off" aria-hidden="true"></i> Logout</a>
  
      {% else %}
      <a href="{% url 'user:login' %}" class="w3-bar-item w3-button w3-hide-small"style = "font-size:20px"><i class="fa fa-sign-in" aria-hidden="true"></i>Login</a>
      {% endif %}
        <a href="{% url 'user:register' %} " class="w3-bar-item w3-button w3-hide-small"style = "font-size:20px"><i class="fa fa-sign-out" aria-hidden="true"></i>Register </a>
        
  
     
    </div>

<title>PysonBlog ✓ - Articles</title>
{% if articles %}
{% for article in articles %}
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
<br><br><br>

<div class="card">
  {% if article.article_image %}
    <a href="{% url 'article:detail' article.id %}" ><img class="img-fluid rounded" src="{{article.article_image.url}}" alt=""  width="300" height = "168"></a>

    {% endif %}
  <a href="{% url 'article:detail' article.id %}"><h2 class="mt-4">{{article.title}}</h2></a>
  <p class="lead">
          by
          {{article.author.username}}
    </p>
    <p>{{article.created_date}}</p>
  <p class="lead"> 
        {{article.content|safe|truncatewords:30}}</p>
        <hr>
  <p><a href="{% url 'article:detail' article.id %}"><button>Devamını oku</button></p></a>
</div>
<br><br><br><hr>
</div>

{% endfor %}

{% else %}
<div class = "row">
    <div class="col-md-10 offset-md-3">
        <div class="col-lg-8">   
            <div class = "alert alert-danger">
            Makale Bulunamadı..
        </div>
        </div>
    </div>
    </div>
</div>
{% endif %}

</html>
</head>
{% endblock body %}
    

templates/dashboard.html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <link rel="stylesheet" href="https://www.w3schools.com/w3css/4/w3.css">
  <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Lato">
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
  <title>Document</title>
  <div class="w3-bar" id="myNavbar">
    <a class="w3-bar-item w3-button w3-hover-black w3-hide-medium w3-hide-large w3-right" href="javascript:void(0);" onclick="toggleFunction()" title="Toggle Navigation Menu">
        <i class="fa fa-bars"></i>
      </a>
      <a href="{% url 'index' %}" class="w3-bar-item w3-button" style = "font-size:20px">PysonBlog ✓</a>
      <a  href="{% url 'article:articles' %}" class="w3-bar-item w3-button w3-hide-small" style = "font-size:20px"><i class="fa fa-clipboard" aria-hidden="true"></i>Articles</a>
      {% if request.user.is_authenticated %}
      <a  href="{% url 'article:dashboard' %}" class="w3-bar-item w3-button w3-hide-small"style = "font-size:20px"><i class="fa fa-wrench" aria-hidden="true"></i>Control Panel</a>
      <a  href="{% url 'user:logout' %}" class="w3-bar-item w3-button w3-hide-small"style = "font-size:20px"><i class="fa fa-power-off" aria-hidden="true"></i> Logout</a>
  
      {% else %}
      <a href="{% url 'user:login' %}" class="w3-bar-item w3-button w3-hide-small"style = "font-size:20px"><i class="fa fa-sign-in" aria-hidden="true"></i>Login</a>
      {% endif %}
        <a href="{% url 'user:register' %} " class="w3-bar-item w3-button w3-hide-small"style = "font-size:20px"><i class="fa fa-sign-out" aria-hidden="true"></i>Register </a>
        
  
     
</div>
  {% if messages %}

            {% for message in messages %}
            {% if message.tags == "info"%}
            <div class="alert alert-danger">{{ message }}</div>
            {% else %}
            <div class="alert alert-{{ message.tags }}">{{ message }}</div>
            
            {% endif %}
           
            {% endfor %}
            
        
        {% endif %}
        <div style = "margin-top : 100px; margin-bottom:100px"  class = "container">
       

  {% block body %}
  
  
  <h3>Kontrol Paneli</h3>
  <hr>
  <p>
  Hoşgeldiniz , <small>{{request.user.username}}</small>
  </p>
  <hr>
  <a class = "btn btn-danger" href = "{% url 'article:addarticle' %}" > Makale Ekle </a>
  <hr>
  {% if articles  %}
  <table class="table">
    <thead class="thead-dark">
      <tr>
        <th scope="col">İD</th>
        <th scope="col">Başlık</th>
        <th scope="col">Yazar</th>
        <th scope="col">Tarih</th>
        <th scope="col">Güncelle</th>
        <th scope="col">Sil</th>
      </tr>
    </thead>
    <tbody>
      {% for article in articles %}
      <tr>
  
      <th scope="row">{{article.id}}</th>
      <td><a href ="{% url 'article:detail' article.id %}">{{article.title}}</td>
      <td>{{article.author.username}}</td>
      <td>{{article.created_date}}</td>
      <td><a href = "{% url 'article:update' article.id %}" class ="btn btn-danger">Güncelle</td>
      <td><a href = "{% url 'article:delete' article.id %}" class ="btn btn-danger">Sil</td>
  
  
  
      </tr>
      {% endfor %}
      <!--<tr>
        <th scope="row">1</th>
        <td>Mark</td>
        <td>Otto</td>
        <td>@mdo</td>
      </tr>-->
      
    </tbody>
  </table>
  {% else %}
  <div class = "alert alert-danger">
  Henüz bir makaleniz bulunmuyor...
  </div>
  
  {% endif %}
  
  {% endblock body %}
</head>
<body>
  
</body>
</html>

templates/detail.html
{% extends "layout.html" %}

{% block body %}

<div class="row">

      <!-- Post Content Column -->
      <div class="col-lg-8">

        <!-- Title -->
        <h3 class="mt-4">{{article.title}}</h3>

        <!-- Author -->
        <p class="lead">
          by
          {{article.author.username}}
        </p>

        <hr>

        <!-- Date/Time -->
        <p>{{article.created_date}}</p>

        <hr>

        <!-- Preview Image -->
        {% if article.article_image %}
        <img class="img-fluid rounded" src="{{article.article_image.url}}" alt="">

        {% endif %}
        

        <hr>

        <!-- Post Content -->
        <p class="lead">
        {{article.content|safe}}</p>
        <hr>
        <h4>Yorumlar</h4>
        <hr>
        {% if comments %}
        {% for comment in comments  %}
        <div class="media mb-4">
          <img class="d-flex mr-3 rounded-circle" src="http://placehold.it/50x50" alt="">
          <div class="media-body">
            <h5 class="mt-0">{{comment.comment_author}}  <br>  {{comment.comment_date}}</h5>
            
            {{comment.comment_content}}

          </div>
        </div>
        {% endfor %}
        
        {% else %}
  <div class = "alert alert-danger">
  Bu makaleye herhangi bir yorum yapılmamış, ilk yorum yapanın siz olmasını ister misiniz?
  </div>

        {% endif %}
<div class="card my-4">
          <h5 class="card-header">Yorum Ekle</h5>
          <div class="card-body">
            <form method = "post" action = "{% url 'article:comment' article.id%}">
            {% csrf_token %}
             <div class="input-group mb-3">
          <div class="input-group-prepend">
          <span  class="input-group-text" id="inputGroup-sizing-default">İsim</span>
          
          </div>
          <input name = "comment_author" type="text" class="form-control" aria-label="Default" aria-describedby="inputGroup-sizing-default">
            </div>

              <div class="form-group">
              <span class="input-group-text" id="inputGroup-sizing-default">Yorum</span>
                <textarea name = "comment_content"  class="form-control" rows="3"></textarea>
              </div>
              <button type="submit" class="btn btn-danger">Ekle</button>
            </form>
          </div>
        </div>
      </div>

      </div>

    </div>
    
{% endblock body %}

templates/login.html
<!DOCTYPE html>
<html lang="en">
<head>
    <title>PysonBlog ✓ - Login</title>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
<style>
@import url(https://fonts.googleapis.com/css?family=Exo:100,200,400);
@import url(https://fonts.googleapis.com/css?family=Source+Sans+Pro:700,400,300);

body{
	margin: 0;
	padding: 0;
	background: #fff;

	color: #fff;
	font-family: Arial;
	font-size: 12px;
}

.body{
	position: absolute;
	top: -20px;
	left: -20px;
	right: -40px;
	bottom: -40px;
	width: auto;
	height: auto;
	background-image: url(https://images.unsplash.com/photo-1491466424936-e304919aada7?ixlib=rb-1.2.1&ixid=MXwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHw%3D&auto=format&fit=crop&w=1349&q=80);
	background-size: cover;
	-webkit-filter: blur(3px);
	z-index: 0;
}

.grad{
	position: absolute;
	top: -20px;
	left: -20px;
	right: -40px;
	bottom: -40px;
	width: auto;
	height: auto;
	background: -webkit-gradient(linear, left top, left bottom, color-stop(0%,rgba(0,0,0,0)), color-stop(100%,rgba(0,0,0,0.65))); /* Chrome,Safari4+ */
	z-index: 1;
	opacity: 0.7;
}

.header{
	position: absolute;
	top: calc(50% - 35px);
	left: calc(50% - 255px);
	z-index: 2;
}

.header div{
	float: left;
	color: #fff;
	font-family: 'Exo', sans-serif;
	font-size: 35px;
	font-weight: 200;
}

.header div span{
	color: #5379fa !important;
}

.login{
	position: absolute;
	top: calc(50% - 75px);
	left: calc(50% - 50px);
	height: 150px;
	width: 350px;
	padding: 10px;
	z-index: 2;
}

.login input[type=text]{
	width: 250px;
	height: 30px;
	background: transparent;
	border: 1px solid rgba(255,255,255,0.6);
	border-radius: 2px;
	color: #fff;
	font-family: 'Exo', sans-serif;
	font-size: 16px;
	font-weight: 400;
	padding: 4px;
}

.login input[type=password]{
	width: 250px;
	height: 30px;
	background: transparent;
	border: 1px solid rgba(255,255,255,0.6);
	border-radius: 2px;
	color: #fff;
	font-family: 'Exo', sans-serif;
	font-size: 16px;
	font-weight: 400;
	padding: 4px;
	margin-top: 10px;
}

.login input[type=button]{
	width: 260px;
	height: 35px;
	background: #fff;
	border: 1px solid #fff;
	cursor: pointer;
	border-radius: 2px;
	color: #a18d6c;
	font-family: 'Exo', sans-serif;
	font-size: 16px;
	font-weight: 400;
	padding: 6px;
	margin-top: 10px;
}

.login input[type=button]:hover{
	opacity: 0.8;
}

.login input[type=button]:active{
	opacity: 0.6;
}

.login input[type=text]:focus{
	outline: none;
	border: 1px solid rgba(255,255,255,0.9);
}

.login input[type=password]:focus{
	outline: none;
	border: 1px solid rgba(255,255,255,0.9);
}

.login input[type=button]:focus{
	outline: none;
}

::-webkit-input-placeholder{
   color: rgba(255,255,255,0.6);
}

::-moz-input-placeholder{
   color: rgba(255,255,255,0.6);
}
h2{
	position: absolute;
	left: -750px;
	top : -280px;
}
</style>
     
{% block body %}
<div class="body"></div>
		<div class="grad"></div>
		<div class="header">
			<div>Pyson<span>Blog ✓</span></div>
		</div>
		<br>
		<div class="login">
            {% load crispy_forms_tags%}
            <div class="row">
                <div class="col-md-6 offset-md-3">
                    <h3>Giriş Yap</h3>
                    <hr>
                    {% load crispy_forms_tags %}
            
                    <form method = "POST">
                        {% csrf_token %}
                        {{form|crispy}}
                        <br>
                        <button type = "submit1" class = "btn btn-primary">Giriş Yap</button>
                        <br><br>
                        

                        
                    
                    </form>
                    <a href="{% url 'user:register'%}"><button type = "submit1" class = "btn btn-danger">Kayıt Ol</button></a>
					<h2><a href="{% url 'index'%}"><button type = "submit1" class = "btn btn-default" >Geri Dön</button></h2></a>
            
                </div>
              </div>
        </div>   
        


{% endblock body %}

templates/update.html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <link rel="stylesheet" href="https://www.w3schools.com/w3css/4/w3.css">
  <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Lato">
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
  <title>Document</title>
  <div class="w3-bar" id="myNavbar">
    <a class="w3-bar-item w3-button w3-hover-black w3-hide-medium w3-hide-large w3-right" href="javascript:void(0);" onclick="toggleFunction()" title="Toggle Navigation Menu">
        <i class="fa fa-bars"></i>
      </a>
      <a href="{% url 'index' %}" class="w3-bar-item w3-button" style = "font-size:20px">PysonBlog ✓</a>
      <a  href="{% url 'article:articles' %}" class="w3-bar-item w3-button w3-hide-small" style = "font-size:20px"><i class="fa fa-clipboard" aria-hidden="true"></i>Articles</a>
      {% if request.user.is_authenticated %}
      <a  href="{% url 'article:dashboard' %}" class="w3-bar-item w3-button w3-hide-small"style = "font-size:20px"><i class="fa fa-wrench" aria-hidden="true"></i>Control Panel</a>
      <a  href="{% url 'user:logout' %}" class="w3-bar-item w3-button w3-hide-small"style = "font-size:20px"><i class="fa fa-power-off" aria-hidden="true"></i> Logout</a>
  
      {% else %}
      <a href="{% url 'user:login' %}" class="w3-bar-item w3-button w3-hide-small"style = "font-size:20px"><i class="fa fa-sign-in" aria-hidden="true"></i>Login</a>
      {% endif %}
        <a href="{% url 'user:register' %} " class="w3-bar-item w3-button w3-hide-small"style = "font-size:20px"><i class="fa fa-sign-out" aria-hidden="true"></i>Register </a>
        
  
     
</div>
  {% if messages %}

            {% for message in messages %}
            {% if message.tags == "info"%}
            <div class="alert alert-danger">{{ message }}</div>
            {% else %}
            <div class="alert alert-{{ message.tags }}">{{ message }}</div>
            
            {% endif %}
           
            {% endfor %}
            
        
        {% endif %}
        <div style = "margin-top : 100px; margin-bottom:100px"  class = "container">
       

{% block body %}
{%load crispy_forms_tags%}
<div class="row">
    <div class="col-md-6 offset-md-3">
        <h3>Makale Güncelle</h3>
        <hr>
        {% load crispy_forms_tags %}

        <form method="POST" enctype="multipart/form-data">

            {% csrf_token %}
            {{form.media}}
            {{form|crispy}}
            <br>
            <button type = "submit1" class = "btn btn-danger">Güncelle</button>
        
        </form>

    </div>
  </div>


{% endblock body %}